02 model spec
KozakuraRyuuichi/sample_app_for_rspec pull request #2
Opened 2020-10-07 15:34 UTC by KozakuraRyuuichi

【概要】
taskモデルのバリデーションに関するテストを作成した。
EverydayRails では、以下の章が対象範囲である。
　3. モデルスペック
　4. 意味のあるテストデータの作成
【確認方法】
・gemを追加したので、bundle installを実行してください。
【確認結果】
・各バリデーションを削除した場合に、テストが失敗することを確認すること。
- `validates :title, presence: true, uniqueness: true`をコメントアウトした場合、キャプチャの通り、テストが失敗することを確認しました。
https://gyazo.com/bfe6f7cc85b28cb82cfa6e1235c238fd

- `validates :status, presence: true`をコメントアウトした場合、キャプチャの通り、テストが失敗することを確認しました。
https://gyazo.com/42f78e45e1760f3aafbb32bd16d547d6

以上、よろしくお願いいたします。

2020-10-08 14:19 UTC, KozakuraRyuuichi commented
## 解答を確認したので下記を修正しました。
- 変数名を役割が分かりやすいように修正  
→ [7b9ec4c](https://github.com/KozakuraRyuuichi/sample_app_for_rspec/pull/2/commits/7b9ec4c2cdf7ec27e2ba7ebcf2c61510d86e92f6)
- `FactoryBot.`を省略  
[71d1812](https://github.com/KozakuraRyuuichi/sample_app_for_rspec/pull/2/commits/71d1812d48284990c4e7aba249e4a01f73066058)
- rspec-rails gemのマッチャでの記述に修正  
[65590ac](https://github.com/KozakuraRyuuichi/sample_app_for_rspec/pull/2/commits/65590ac350d07d7809258bcce8f51c3ff6bcd06d)

## 質問
- `it "is invalid without title"`のようなテストの場合は、DB連携させる必要がないので、動作のスピード重視で`build`で書いてるということでしょうか？

2020-10-09 02:42 UTC, yuji91 requested changes
> it "is invalid without title"のようなテストの場合は、DB連携させる必要がないので、動作のスピード重視でbuildで書いてるということでしょうか？

はい。必要がないのでDBアクセスを発生させないように記載する形になりますね。

2020-10-09 02:42 UTC, yuji91 commented on spec/factories/users.rb
> +    sequence(:email, "user1@sample.com")
存在しないことが保証されているドメインである`example.com`を使うようにしましょう。
```suggestion
    sequence(:email, "user1@example.com")
```

2020-10-09 02:42 UTC, yuji91 commented on spec/factories/users.rb
> +    password_confirmation {"password"}
波括弧（ブレース）の中はスペースで区切った方が見やすいですね。
```suggestion
    password { "password" }
    password_confirmation { "password" }
```

2020-10-09 02:42 UTC, yuji91 commented on spec/models/task_spec.rb
> +      task_with_another_title = build(:task, title: "title2")
細かい部分ですが、できるだけ数字などではなく意味のある適切な名前をつけるようにしましょう。
```suggestion
      task_with_another_title = build(:task, title: "another_title")
```

2020-10-09 02:42 UTC, yuji91 commented on spec/spec_helper.rb
> +require 'factory_bot_rails'
この定義は必要なかった気がするので、ご確認頂きたいです。

2020-10-09 03:27 UTC, KozakuraRyuuichi commented on spec/factories/users.rb
> +    sequence(:email, "user1@sample.com")
了解しました！

2020-10-09 03:27 UTC, KozakuraRyuuichi commented on spec/factories/users.rb
> +    password_confirmation {"password"}
確かにそちらの方が見やすいですね。修正します。

2020-10-09 04:04 UTC, KozakuraRyuuichi commented on spec/models/task_spec.rb
> +      task_with_another_title = build(:task, title: "title2")
修正します！

2020-10-09 11:55 UTC, KozakuraRyuuichi commented on spec/spec_helper.rb
> +require 'factory_bot_rails'
FactoryBotが上手く生成されなかたっときに試したものが残ってしまっていました。
必要ないので、修正します。

2020-10-09 11:56 UTC, KozakuraRyuuichi commented
質問の解答ありがとうございました。
認識があっててよかったです。
修正して再PRいたします。

2020-10-09 12:30 UTC, KozakuraRyuuichi commented on spec/spec_helper.rb
> +require 'factory_bot_rails'
`require 'factory_bot_rails'`をコメントアウトして`bundle exec rspec`を実行すると下記のようにエラーが出ます。

`NameError:  uninitialized constant FactoryBot`を元に調べて、いくつか対応してみましたが、  
`require 'factory_bot_rails'の定義を入れないとエラーが解消されない状態です。
[エラー内容](https://gyazo.com/1d0ab325074c34f594bed01ce9311e93)

【対応１】  
factory_bot_railsのバージョンを5.2.0に変更する。  
[参考記事](https://qiita.com/hattiy/items/4f724419bfd355179b26)  
結果は、同様のエラーでした。

【対応２】  
`config.include FactoryBot::Syntax::Methods`を`spec_helper.rb`の最後に書く。
[参考記事](https://qiita.com/blackpeach7/items/fae79ba209499de4bdff)  
結果は、こちらも同様のエラーでした。

【対応３】  
`require 'factory_bot_rails'`を定義する。  
[参考記事](http://rails.takayukikoyama.com/rspec/rspec-factorygirl/)
ここちらを行うと、テストが成功します。

ご教授よろしくお願いいたします。

2020-10-10 04:51 UTC, yuji91 commented on spec/spec_helper.rb
> +require 'factory_bot_rails'
承知しました。定義する形で大丈夫です！
こちら定義する際に、コミットを分けて追加できると良かったかもしれないですね。

2020-10-10 04:52 UTC, yuji91 commented on spec/factories/users.rb
> +    password_confirmation {"password"}
修正の際はこちらのコメント欄に対応するコミットIDを半角スペース区切りで返答する形でお願いします。

2020-10-10 14:06 UTC, KozakuraRyuuichi commented on spec/factories/users.rb
> +    password_confirmation {"password"}
こちらで修正しました。
[84c91b7](https://github.com/KozakuraRyuuichi/sample_app_for_rspec/pull/2/commits/84c91b7e930dbc28facf1851e00d2be8801c99d4)

2020-10-10 14:08 UTC, KozakuraRyuuichi commented on spec/models/task_spec.rb
> +      task_with_another_title = build(:task, title: "title2")
変数名はこちらで修正しました。
[a09b2cc](https://github.com/KozakuraRyuuichi/sample_app_for_rspec/pull/2/commits/a09b2cc2c0314276206e0d4b3dad7401bf159185)

2020-10-10 14:10 UTC, KozakuraRyuuichi commented on spec/spec_helper.rb
> +require 'factory_bot_rails'
了解いたしました！
require 'factory_bot_rails'の定義はこちらで修正しました。
[d6d831c](https://github.com/KozakuraRyuuichi/sample_app_for_rspec/pull/2/commits/d6d831c47ee9e0f442c9b88145ddbf5ec3025c9a)

2020-10-10 14:13 UTC, KozakuraRyuuichi commented
> はい。必要がないのでDBアクセスを発生させないように記載する形になりますね。
ありがとうございます。認識と合っていたのでよかったです。
修正いたしましたので、ご確認よろしくお願いいたします。

2020-10-11 01:29 UTC, yuji91 requested changes
後1点直したらOKなので、マージして次の課題に進んでください！

2020-10-11 01:29 UTC, yuji91 commented on spec/spec_helper.rb
> +  # config.include FactoryBot::Syntax::Methods
コメントの消し忘れがあるようです

2020-10-11 03:15 UTC, KozakuraRyuuichi commented on spec/spec_helper.rb
> +  # config.include FactoryBot::Syntax::Methods
こちらでコメント削除しました
[c1c097c](https://github.com/KozakuraRyuuichi/sample_app_for_rspec/pull/2/commits/c1c097c4572052e1211218fea8f8b599af8ddf99)

2020-10-11 03:15 UTC, KozakuraRyuuichi commented
ありがとうございます。
次に進みます！

2020-10-11 03:16 UTC, merged