03 system spec
KozakuraRyuuichi/sample_app_for_rspec pull request #3
Opened 2020-10-18 15:54 UTC by KozakuraRyuuichi

【概要】
・taskのシステムスペックの作成
・userのシステムスペックの作成
・user_sessionのシステムスペックの作成
【確認方法】
・gemを追加したので、bundle installを実行してください。
・modelのバリデーションを無効にして、テスト結果がエラーになるかご確認ください。
【確認結果】
・taskのシステムスペック結果
![Uploading taskのシステムスペック結果.png…]()

・userのシステムスペック結果
![Uploading userのシステムスペック結果.png…]()

・user_sessionのシステムスペック結果
<img width="237" alt="user_sessionのシステムスペック結果" src="https://user-images.githubusercontent.com/56499977/96373158-94e14780-11a5-11eb-9a29-045d6296b216.png">

2020-10-21 12:56 UTC, KozakuraRyuuichi commented
いくつか質問させてください

- 'tasks_spec.rb'のタスク一覧にアクセスするテストにおいて、ページ遷移後の'expect(current_path).to eq tasks_path'も必要でしょうか？？'visit tasks_path'からページ遷移していないので必要と思わず、元々は記述していませんでした。
[8f4dac7](https://github.com/KozakuraRyuuichi/sample_app_for_rspec/pull/3/commits/8f4dac7b0303293bb03105e099a4dbb701546155)

- 例えば'tasks_spec.rb'において、'visit new_task_path'を'click_on ‘New Task’'のようにユーザーの実際の動き通りに記載するのはでは、なにか問題あるのでしょうか？テストとは関係ない所の記述をより少なく完結にするためでしょうか？

- タスク削除のテストで、解答には'expect(page.accept_confirm).to eq 'Are you sure?''とあるところを'page.driver.browser.switch_to.alert.accept 'と記述しました。良し悪しをコメント頂きたいです。
[1a337ff](https://github.com/KozakuraRyuuichi/sample_app_for_rspec/pull/3/commits/1a337ffcd4b2ac3fb8181fe6851902a54b9abf4f)

2020-10-22 05:35 UTC, yuji91 commented
> 'tasks_spec.rb'のタスク一覧にアクセスするテストにおいて、ページ遷移後の'expect(current_path).to eq tasks_path'も必要でしょうか？？

確かにここは無くても大丈夫ですね！

> 例えば'tasks_spec.rb'において、'visit new_task_path'を'click_on ‘New Task’'のようにユーザーの実際の動き通りに記載するのはでは、なにか問題あるのでしょうか？
> テストとは関係ない所の記述をより少なく完結にするためでしょうか？

簡潔にするためですね！
もし特定の画面に遷移する際に、画面上の操作によってそこに移動したい場合は、beforeなどでまとめたり、Moduleとして処理を切り出すと記載が減って見やすくなるので良いかと思います。

一般的には、必要なければ`visit`で簡潔に記載するという認識で大丈夫です。

2020-10-22 05:56 UTC, yuji91 requested changes
すごく丁寧で良いと思います！
細かい点の指摘だけしておくので、次の修正編にも着手していてOKです！

2020-10-22 05:56 UTC, yuji91 commented on spec/spec_helper.rb
> +# require 'factory_bot_rails'
コメントアウトするなら削除してしまっても良いかもです

2020-10-22 05:56 UTC, yuji91 commented on spec/support/login_module.rb
> +  def login(user)
好みなので修正しなくても大丈夫ですが、以下のように少し読みやすいメソッド名にしてもいいかも、です
```ruby
# 使用例
admin_user = create(:user, admin: true)
login_as(admin_user)
```

```suggestion
  def login_as(user)
```

2020-10-22 05:56 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +          expect(page).to have_content("Title has already been taken")
1つ上のコードと記法を統一してもいいかもです
```suggestion
          expect(page).to have_content 'Title has already been taken'
```

2020-10-22 05:56 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +          expect(page).to have_content("Task was successfully updated.")
ちなみに、このように, で区切ってカスタムエラーメッセージを定義することもできるので共有いたします。
```suggestion
          expect(page).to have_content("Task was successfully updated."), "タスク更新完了のメッセージが表示されていません。"
```

2020-10-22 05:56 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +        it 'タスク作成に失敗するる' do
直しておいてもいいかもです
```suggestion
        it 'タスク作成に失敗する' do
```

2020-10-22 13:25 UTC, KozakuraRyuuichi commented
質問の解答ありがとうございます！

> こちらは好みなのでどちらでも大丈夫です！
強いて言えば、回答だとAre you sure?という文言も確認しているので、この文言を特定の単語で固定したいのであれば文言も含めて確認、特に意図がなければ文言を含めないで確認、と行った形で使い分けても良いかもしれません。  
解答の方がパッと見てわかりやすいし、「Are you sure?を確認してOkする」の方がテストとしてはいいのかな？と思ったので、解答を反映する形にしようと思います。

> そうですね、今回の内容では、以下のようなざっくりとした分け方でもいいかと思います。
Add: RSpec用のgemを追加
Add: taskのシステムスペックの作成
Add: userのシステムスペックの作成
Add: user_sessionのシステムスペックの作成
Modify: 設定ファイルの変更  

ここも非常に勉強になりました。実装においてもコミットのアウトラインを予想しておいた方が良いなと想いました。
実装し終わってからコミットの形を考える、ということが多かったので参考にします。

> また、コミットの粒度については現場によって異なるため、現場のルールやコミット済のファイルの履歴を見るなどしてどのくらいの細かさが適切かを判断して行う形になりますね。  
これ！という正解があるわけではない、と理解したので、レビューしやすさを意識してみます。

2020-10-22 13:26 UTC, KozakuraRyuuichi commented on spec/spec_helper.rb
> +# require 'factory_bot_rails'
了解いたしました。削除します！

2020-10-22 13:27 UTC, KozakuraRyuuichi commented on spec/support/login_module.rb
> +  def login(user)
こちらの方が読みやすいので修正いたします。
ありがとうございます。

2020-10-22 13:27 UTC, KozakuraRyuuichi commented on spec/system/tasks_spec.rb
> +          expect(page).to have_content("Title has already been taken")
これも修正します。

2020-10-22 13:28 UTC, KozakuraRyuuichi commented on spec/system/tasks_spec.rb
> +        it 'タスク作成に失敗するる' do
修正します。

2020-10-22 13:32 UTC, KozakuraRyuuichi commented on spec/system/tasks_spec.rb
> +          expect(page).to have_content("Task was successfully updated.")
共有ありがとうございます。

> 私は、エラーがたくさんでてわかりにくいときに、間違っている可能性がある場所を記述するのに使ってみています。

エラー内容を把握しやすくするためってことですね。
テスト量が増えると便利なのかなっと思いました。ありがとうございます！！

http://tkymtk.hatenablog.com/entry/rspec-customized-error-message-2013-12

2020-10-22 14:29 UTC, merged

2020-10-22 17:22 UTC, yuji91 commented
指摘事項を別のPRで行うことは現場では通常行わないので、その点だけ覚えておいてもらえると良いかと思いますm(_ _)m（レビュアーが指摘した修正事項の対応状況が把握できないためです）

2020-10-22 17:31 UTC, KozakuraRyuuichi commented
> 指摘事項を別のPRで行うことは現場では通常行わないので、その点だけ覚えておいてもらえると良いかと思いますm(_ _)m（レビュアーが指摘した修正事項の対応状況が把握できないためです）  

今回であれば、03 system specでの修正はこのPR内で完結するのが望ましい、という理解でよろしいでしょうか？
そうであれば了解いたしました。
たしかにPRが分かれると、フォローが難しいなと思いました。
ありがとうございます！